#!/bin/bash

sleep 10

PFAD=/storage/UBUNTU/vdr

cd /storage/UBUNTU/vdr
NEXT=ambion;

while true;
do
   case "$NEXT" in
  "ambioff")
       ./looperambi
       systemctl stop service.hyperion.ng 
       NEXT=ambion;
       ;;
   "ambion")
       ./looperambi
       systemctl start service.hyperion.ng
       NEXT=ambioff;
       ;;
    esac
done

